### ISSUE TITLE
volspotconnect2 panic 

### ISSUE THREAD

**Issue by andycowan** [ashthespy/Volumio-SpotifyConnect#4]
When I try to connect from the Spotify desktop client, the connection appears to establish and then drops immediately. The following is generated in the logs:
```
volumio@bango:~/volspotconnect2$ journalctl -f -o cat -u volspotconnect2.service
31: 0x76cb0678 - __libc_start_main
[Vollibrespot] : EventSender disconnected
volspotconnect2.service holdoff time over, scheduling restart.
Stopping Volspotconnect2 Daemon...
Starting Volspotconnect2 Daemon...
Started Volspotconnect2 Daemon.
vollibrespot v0.2.2 cd96399 2020-10-07 (librespot 08d8bcc 2020-10-07) -- Built On 2020-10-07
Reading Config from "volspotify.toml"
[Vollibrespot] : Using Alsa backend with device: plughw:2
[Vollibrespot] : Failed to register IPv6 receiver: Os { code: 19, kind: Other, message: "No such device" }
[Vollibrespot] : Connecting to AP "gew1-accesspoint-a-dpb2.ap.spotify.com:443"
[Vollibrespot] : Authenticated as "1167037385" !
[Vollibrespot] : Setting up new mixer: card:hw:2 mixer:Digital index:0
[Vollibrespot] : Alsa Mixer info min: 0 (MilliBel(-9999999)[dB]) -- max: 207 (MilliBel(0)[dB]) HW: true
[Vollibrespot] : Using alsa sink
[Vollibrespot] : Metadata pipe established
[Vollibrespot] : Country: "GB"
[Vollibrespot] : Event: Volume { volume_to_mixer: 16383 }
[Vollibrespot] : Fetching autoplay context uri
[Vollibrespot] : Event: SessionActive { became_active_at: 1638207407785 }
[Vollibrespot] : SessionActive!
[Vollibrespot] : Event: PlaybackStarted { track_id: SpotifyId { id: 316107200284235207208001193206148091926, audio_type: Track } }
[Vollibrespot] : Event: PlaybackLoading { track_id: SpotifyId { id: 316107200284235207208001193206148091926, audio_type: Track } }
[Vollibrespot] : error 403 for uri hm://keymaster/token/authenticated?client_id=4ced2e7c73484127be5d36015752eb43&scope=streaming,user-read-playback-state,user-modify-playback-state,user-read-currently-playing,user-read-private
[Vollibrespot] : Error: MercuryError
[Vollibrespot] : Autoplay uri resolved to <"spotify:station:album:7ipY0pDn2DQBP8F3q8wC2a">
[Vollibrespot] : Resolving uri "spotify:station:album:7ipY0pDn2DQBP8F3q8wC2a"
thread 'main' panicked at 'cannot poll Map twice', /build/cache/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/map.rs:35:29
stack backtrace:
0:   0x9ec33c - backtrace::backtrace::libunwind::trace::hae21a072c81e5842
at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
1:   0x9ec33c - backtrace::backtrace::trace_unsynchronized::h0f9b260087e46e47
at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
2:   0x9ec33c - std::sys_common::backtrace::_print_fmt::hbf1a59173a7860c3
at src/libstd/sys_common/backtrace.rs:78
3:   0x9ec33c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he1a5d6f378e506c4
at src/libstd/sys_common/backtrace.rs:59
4:   0xa0cd5c - core::fmt::write::hb37ae5a5e0b70623
at src/libcore/fmt/mod.rs:1076
5:   0x9e5c64 - std::io::Write::write_fmt::ha24bb3f5a858327b
at src/libstd/io/mod.rs:1537
6:   0x9ee974 - std::sys_common::backtrace::_print::h47b03aa1342833e3
at src/libstd/sys_common/backtrace.rs:62
7:   0x9ee974 - std::sys_common::backtrace::print::h2217cbc390250439
at src/libstd/sys_common/backtrace.rs:49
8:   0x9ee974 - std::panicking::default_hook::{{closure}}::h179f5229ea1c8e30
at src/libstd/panicking.rs:198
9:   0x9ee640 - std::panicking::default_hook::h46ab82039cbc65eb
at src/libstd/panicking.rs:217
10:   0x9ef054 - std::panicking::rust_panic_with_hook::h7326c48419bc7c33
at src/libstd/panicking.rs:526
11:   0x9eec54 - rust_begin_unwind
at src/libstd/panicking.rs:437
12:   0xa0a594 - core::panicking::panic_fmt::ha292e19d5ae716ed
at src/libcore/panicking.rs:85
13:   0xa0a370 - core::option::expect_failed::he9e39f8f5ba60ecb
at src/libcore/option.rs:1261
14:   0x6e0bf8 - <futures::future::map::Map<A,F> as futures::future::Future>::poll::h3d56b212ca27d9e4
15:   0x5963a4 - <librespot_connect::spirc::SpircTask as futures::future::Future>::poll::ha2e91a6b75c719f3
16:   0x50cca4 - <vollibrespot::Main as futures::future::Future>::poll::hc5e7d2d1b7dbef13
17:   0x4d4844 - futures::task_impl::std::set::h8f081cf0436110c9
volspotconnect2.service: main process exited, code=exited, status=101/n/a
Unit volspotconnect2.service entered failed state.
18:   0x4e841c - std::thread::local::LocalKey<T>::with::h711a13323aafc45a
19:   0x4c4a50 - tokio_current_thread::Entered<P>::block_on::h339073902a399eb7
20:   0x4e8e00 - std::thread::local::LocalKey<T>::with::hff64c13ccfec5327
21:   0x4f520c - tokio_reactor::with_default::h7ef12e65cb103d2f
22:   0x4c89f8 - tokio::runtime::current_thread::runtime::Runtime::block_on::h043f136d6b8cf48f
23:   0x50e2c8 - vollibrespot::main::h02a0d49d4cc5eaa6
24:   0x4f5f18 - std::rt::lang_start::{{closure}}::h279cd2b7929fdba7
25:   0x9ef404 - std::rt::lang_start_internal::{{closure}}::he93bfc404849b78a
at src/libstd/rt.rs:52
26:   0x9ef404 - std::panicking::try::do_call::h6e9e98f4078affb0
at src/libstd/panicking.rs:348
27:   0x9ef404 - std::panicking::try::h2e68d4f7f799a6df
at src/libstd/panicking.rs:325
28:   0x9ef404 - std::panic::catch_unwind::h8880a4c07cc66391
at src/libstd/panic.rs:394
29:   0x9ef404 - std::rt::lang_start_internal::hf4ae2140248bf16b
at src/libstd/rt.rs:51
30:   0x50ed84 - main
31: 0x76c5d678 - __libc_start_main
[Vollibrespot] : EventSender disconnected
volspotconnect2.service holdoff time over, scheduling restart.
Stopping Volspotconnect2 Daemon...
Starting Volspotconnect2 Daemon...
Started Volspotconnect2 Daemon.
vollibrespot v0.2.2 cd96399 2020-10-07 (librespot 08d8bcc 2020-10-07) -- Built On 2020-10-07
Reading Config from "volspotify.toml"
[Vollibrespot] : Using Alsa backend with device: plughw:2
[Vollibrespot] : Failed to register IPv6 receiver: Os { code: 19, kind: Other, message: "No such device" }
```

**Comment by andycowan** [comment]
Fixed this by adding a username and password in the settings using a device username/password from the spotify account.

Suggest an error message coming from the 403 status might be more helpful?

**Comment by csaavedra** [comment]
This should be reopened because this still happens. If one is not authenticated, the error appears. I don't think logging in with credentials should be considered as a fix for this, the error shouldn't be happening. Plugin version 3.0.9.

```
Starting Live Log...
[Vollibrespot] : Failed to register IPv6 receiver: Os { code: 19, kind: Uncategorized, message: "No such device" }

info: CoreCommandRouter::volumioGetState
info: CoreCommandRouter::volumioGetQueue
info: CoreStateMachine::getQueue
info: CorePlayQueue::getQueue
info: CoreCommandRouter::executeOnPlugin: system , getHwuuid
info: CALLMETHOD: system_controller system enableLiveLog true
info: CoreCommandRouter::executeOnPlugin: system , enableLiveLog
info: Launching a new LiveLog session
[Vollibrespot] : Connecting to AP "ap-gew4.spotify.com:443"
[Vollibrespot] : Authenticated as "csaavedra" !
[Vollibrespot] : Using alsa sink
[Vollibrespot] : Metadata pipe established
[Vollibrespot] : Event: Volume { volume_to_mixer: 65535 }
[Vollibrespot] : Country: "FI"
[SpotifyConnect] Volume Spotify: 100 Volumio: 100
[Vollibrespot] : Fetching autoplay context uri
[Vollibrespot] : Event: SessionActive { became_active_at: 1691564591590 }
[Vollibrespot] : SessionActive!
[Vollibrespot] : Event: PlaybackStarted { track_id: SpotifyId { id: 98879999662705976983520128789562931269, audio_type: Track } }
[Vollibrespot] : Event: PlaybackLoading { track_id: SpotifyId { id: 98879999662705976983520128789562931269, audio_type: Track } }
[SpotifyConnect]  A connect session has begun
[SpotifyConnect]  Device palyback is active!
[SpotifyConnect]  Device palyback is loading
[Vollibrespot] : error 403 for uri hm://keymaster/token/authenticated?client_id=4ced2e7c73484127be5d36015752eb43&scope=streaming,user-read-playback-state,user-modify-playback-state,user-read-currently-playing,user-read-private
[Vollibrespot] : Error: MercuryError
[Vollibrespot] : Autoplay uri resolved to <"spotify:station:album:2v6ANhWhZBUKkg6pJJBs3B">
[Vollibrespot] : Resolving uri "spotify:station:album:2v6ANhWhZBUKkg6pJJBs3B"
thread 'main' panicked at 'cannot poll Map twice', /build/cache/registry/src/github.com-1ecc6299db9ec823/futures-0.1.31/src/future/map.rs:35:29
stack backtrace:
   0:   0x9f8444 - std::backtrace_rs::backtrace::libunwind::trace::h40a4eff66330a36d
                       at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:   0x9f8444 - std::backtrace_rs::backtrace::trace_unsynchronized::hbce01963451b0cd5
                       at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:   0x9f8444 - std::sys_common::backtrace::_print_fmt::h95da650d09c7e00b
                       at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:66:5
   3:   0x9f8444 - ::fmt::h33b23b1d14f668ff
                       at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:45:22
   4:   0xa210dc - core::fmt::write::h6320fb0e6ac90e58
                       at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/fmt/mod.rs:1190:17
   5:   0x9f04c4 - std::io::Write::write_fmt::h33b25d4810ca481f
                       at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/mod.rs:1657:15
   6:   0x9faef4 - std::sys_common::backtrace::_print::h7e61c5be69c715ef
                       at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:48:5
   7:   0x9faef4 - std::sys_common::backtrace::print::h3cee176d7c8dab8b
                       at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:35:9
   8:   0x9faef4 - std::panicking::default_hook::{{closure}}::h2d0211dd2e97dc43
                       at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:295:22
   9:   0x9fab14 - std::panicking::default_hook::hcbdb3b7c40dca30c
                       at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:314:9
  10:   0x9fb694 - std::panicking::rust_panic_with_hook::h4ce49e7a343dc12b
                       at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:698:17
  11:   0x9fb304 - std::panicking::begin_panic_handler::{{closure}}::h4961100fae529fe9
                       at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:588:13
  12:   0x9f89c4 - std::sys_common::backtrace::__rust_end_short_backtrace::hf2e68e62c7a80f1f
                       at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18
  13:   0x9fb098 - rust_begin_unwind
                       at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
  14:   0x4de6f4 - core::panicking::panic_fmt::h84c42730e4a50809
                       at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
  15:   0xa1df88 - core::panicking::panic_display::he50fbe261a13d083
                       at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:73:5
  16:   0xa1df38 - core::panicking::panic_str::h6e4cfb6a94cf14e8
                       at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:56:5
  17:   0x4de57c - core::option::expect_failed::h5f2b901fbc810215
                       at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/option.rs:1852:5
  18:   0x740e18 -  as futures::future::Future>::poll::h794cc547cc6bc145
  19:   0x5c9d78 - ::poll::h2a7bff75029d3b82
  20:   0x5062ec - ::poll::h5fd9e3bcdeb25ad9
  21:   0x5233dc - futures::task_impl::std::set::h8f754e80bd562d0a
  22:   0x53a42c - std::thread::local::LocalKey::with::h71cfa1e374fcc0a0
  23:   0x51f99c - tokio_current_thread::Entered
::block_on::hde55cdf28eabe6d5
  24:   0x53a6f0 - std::thread::local::LocalKey::with::hedba3cfe41326627
  25:   0x522880 - tokio::runtime::current_thread::runtime::Runtime::block_on::h60d5b89560100ed8
  26:   0x508eb0 - vollibrespot::main::h35555355ed947dd1
  27:   0x528c50 - std::sys_common::backtrace::__rust_begin_short_backtrace::hef626a10d324c12a
  28:   0x54e52c - std::rt::lang_start::{{closure}}::hd80188e4bcac5072
  29:   0x9f7b28 - core::ops::function::impls:: for &F>::call_once::h0567da839a080232
                       at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:259:13
  30:   0x9f7b28 - std::panicking::try::do_call::hdf194554a41aa3cc
                       at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  31:   0x9f7b28 - std::panicking::try::hbf4b7be9f9ffa5f8
                       at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  32:   0x9f7b28 - std::panic::catch_unwind::h45f392a39f2fe48c
                       at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  33:   0x9f7b28 - std::rt::lang_start_internal::{{closure}}::hd772cb03c2060671
                       at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:128:48
  34:   0x9f7b28 - std::panicking::try::do_call::hd126f715b519ff2a
                       at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  35:   0x9f7b28 - std::panicking::try::h80b7148ce71893dc
                       at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  36:   0x9f7b28 - std::panic::catch_unwind::h1562f0b2e8a9cb0d
                       at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  37:   0x9f7b28 - std::rt::lang_start_internal::h3daa586a0b835507
                       at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:128:20
  38:   0x50ae80 - main
  39: 0x76bc3768 - __libc_start_main
[Vollibrespot] : EventSender disconnected
[SpotifyConnect]  PlaybackInactive
info: [1691564591756] ControllerSpotify::pushState
info: CoreCommandRouter::servicePushState
info: CoreStateMachine::pushState
volspotconnect.service: Main process exited, code=exited, status=101/n/a
info: CoreCommandRouter::volumioPushState
volspotconnect.service: Failed with result 'exit-code'.
```

**Comment by ashthespy** [comment]
This plugin isn't being maintained by me any longer - it's been integrated into [volumio-plugins-sources](https://github.com/volumio/volumio-plugins-sources/issues) you should open an issue there :-)

**Comment by csaavedra** [comment]
I did already apparently a month ago :) https://github.com/volumio/volumio-plugins-sources/issues/236

**Comment by ashthespy** [comment]
Ah, well, you'll have to follow up there (or their forums) unfortunately.. 
It it would seem Volumio's fork (https://github.com/volumio/Vollibrespot/tree/0.4.2) is tracking upstream, so you'd have to ask them. 

The 403 error indicates they are some issues with how the authentication is being carried out. Good luck! :-)
